apiVersion: apps/v1
kind: Deployment
metadata:
  name: foundryvttver9
  labels:
    app: foundryvtt
spec:
  selector:
    matchLabels:
      app: foundryvtt
      tier: foundryvttver9
  replicas: 1
  template:
    metadata:
      labels:
        app: foundryvtt
        tier: foundryvttver9
    spec:
      containers:
      - name: foundryvtt
        image: public.ecr.aws/c8t2w4a7/foundryvttver9:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # Using `GET_HOSTS_FROM=dns` requires your cluster to
          # provide a dns service. As of Kubernetes 1.3, DNS is a built-in
          # service launched automatically. However, if the cluster you are using
          # does not have a built-in DNS service, you can instead
          # access an environment variable to find the master
          # service's host. To do so, comment out the 'value: dns' line above, and
          # uncomment the line below:
          # value: env
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: foundryloadbalancer
  labels:
    app: foundryvtt
    tier: foundryvttver9
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  #type: NodePort
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: foundryvtt
    tier: foundryvttver9
