apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: http-ingress
spec:
  rules:
  - http:10.152.183.28
      paths:
      - path: /
        backend:
          serviceName: foundryvtt-service
          servicePort: 80
